// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANb2OxQPQHwfSeHRSFV81iFzZeiADt5E',
    appId: '1:551496556472:web:0c7b4c9fb90e83cee0394d',
    messagingSenderId: '551496556472',
    projectId: 'petsync-606d4',
    authDomain: 'petsync-606d4.firebaseapp.com',
    storageBucket: 'petsync-606d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGCZckBEnKhGzFmOPArjwhX30yAOxYpXk',
    appId: '1:551496556472:android:0b1a7a2910ef201de0394d',
    messagingSenderId: '551496556472',
    projectId: 'petsync-606d4',
    storageBucket: 'petsync-606d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEMJLk3m73tC7cWNfmnDhLV_9Mw8YhYqI',
    appId: '1:551496556472:ios:178e8dede31ea202e0394d',
    messagingSenderId: '551496556472',
    projectId: 'petsync-606d4',
    storageBucket: 'petsync-606d4.firebasestorage.app',
    iosBundleId: 'com.example.petsync',
  );
}
